version: '3.4'

services:
  filmDb:
    container_name: filmDb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  docker.template.mongo:
    container_name: docker.template.mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://filmDb:27017
    depends_on:
      - filmDb
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro